name: Vala Code
desc: Vala support for Visual Studio Code
permalink: /:name/
excerpt_separator: ""
repro: vala-code-web
exclude:
  - pubspec.yaml  
collections:
  docs:
    output: true
    permalink: /docs/:name/
  tools:
    output: true
    permalink: /tools/:name/
  releases:
    output: true
    permalink: /releases/:name/
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: "_docs"
      type: docs
    values:
      layout: doc
  - scope:
      path: "_tools"
      type: tools
    values:
      layout: tool
  - scope:
      path: _releases
      type: releases
    values:
      layout: release
